apiVersion: apps/v1
kind: Deployment
metadata:
  name: b2bhello-deployment
  labels:
    app: b2bhello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b2bhello
  template:
    metadata:
      labels:
        app: b2bhello
    spec:
      containers:
      - name: b2bhello
        image: hello:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
